### ISSUE TITLE
Error Could not find motor definition '[motor_constants fysetc-17hs19-2004s-c]' despite being in config

### ISSUE THREAD

**Issue by WaschBaer0395** [andrewmcgr/klipper_tmc_autotune#122]
Error Could not find motor definition '[motor_constants fysetc-17hs19-2004s-c]' 
since the latest update i get this error, the motor is 100% in the config 
![image](https://github.com/andrewmcgr/klipper_tmc_autotune/assets/20116679/700d3157-18cb-4c5d-bc95-6557887e68d0)
![image](https://github.com/andrewmcgr/klipper_tmc_autotune/assets/20116679/7875ed40-7b46-4d59-a237-8f63637bd260)
![image](https://github.com/andrewmcgr/klipper_tmc_autotune/assets/20116679/d4ede05b-cc8c-430d-a09f-bb74bbe88b03)

**Comment by SvenANT** [comment]
Hi, I had the same issue, don't use capital letters in your [motor_constants xxx] name or in your "motor: xxx". I was pulling my hair out too :)

**Comment by ScorpSoul** [comment]
Same, changes all to lowercase on the database and it worked

**Comment by WaschBaer0395** [comment]
yea someone messed up and didnt check if the database still works after they removed whatever converted all names to be lowercase ( why remove that anyways .. dont see a reason to remove that )
