### ISSUE TITLE
Section 'motor_constants 17hs4401s' is not a valid config section

### ISSUE THREAD

**Issue by IspanMiki** [andrewmcgr/klipper_tmc_autotune#164]
I had this issue after an update. Just writing this becasue I didn't find anything related online. Maybe it will help someone in the future. 
So, the only thing helped me is to remove the tmc autotune directory on the host and reinstall it. I have kept everything in klipper, and after the reinstall it worked again perfectly.

**Comment by dhruvinsh** [comment]
going through same issue right now.
