### ISSUE TITLE
config settings for BJ42D25-26V09 and BJ42D22-23V01

### ISSUE THREAD

**Issue by poudenes** [andrewmcgr/klipper_tmc_autotune#165]
Hi All,

Does someone have the custom config settings for those 2 motors?

BJ42D25-26V09 (xyz)
BJ42D22-23V01 (extruder)

Thanks,
Peter

**Comment by lotfinoluffy** [comment]
thni its the motor named creality 42-34 one for the ender 3

**Comment by poudenes** [comment]
Ohh im sorry. Yes it was indeed labeled 42-34 and in the information it was already there.
Forgotten to close this issue
