### ISSUE TITLE
Internal error on commands: "HYPERLAPSE" and "UPDATE_DELAYED_GCODE"

### ISSUE THREAD

**Issue by Vooks916** [andrewmcgr/klipper_tmc_autotune#80]
When defining the autotune_tmc sections for each motor, I am getting an error related to timelapse? This only occurs when using the autotune on motors z2, z3, and extruder on a V2.4. If I only define autotune for any combination of z0, z1, x, and y, no errors are thrown. Klipper, along with everything else on my printer, is fully up to date.
<img width="1098" alt="Errors" src="https://github.com/andrewmcgr/klipper_tmc_autotune/assets/74394627/45fe35ad-7247-4d93-97eb-ee784b303fa9">
[klippy(7).log](https://github.com/andrewmcgr/klipper_tmc_autotune/files/13064705/klippy.7.log)

**Comment by LongDono** [comment]
In my Trident config, Klipper will not start if I have all 3 Z motors defined. If I disabled Z1 or Z2, it starts up. 

![image](https://github.com/andrewmcgr/klipper_tmc_autotune/assets/5301311/eda3637e-e94d-4af5-ad32-a61bbd4574a0)

**Comment by Samuel-0-0** [comment]
Too，it conflict with moonraker-timestamp
https://github.com/mainsail-crew/moonraker-timelapse
